version: "3"
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: ${MODE}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./defaults/shiroxy.conf.yaml:/app/defaults/shiroxy.conf.yaml
    command: /app/build/shiroxy -c /app/defaults/shiroxy.conf.yaml
