version: "3.8"

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    command: /app/shiroxy -c /app/defaults/shiroxy.conf.yaml
