services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "2210:2210"
    volumes:
      - ./defaults/shiroxy.conf.yaml:/app/defaults/shiroxy.conf.yaml
    command: /app/build/shiroxy -c /app/defaults/shiroxy.conf.yaml
