[default]
mode = "http"
logpath = "/home/shikharcode/Main/opensource/shiroxy"
datapersistancepath = "/home/shikharcode/Main/opensource/shiroxy"
enablednschallengesolver = ""

[default.timeout]
connect = "10s"
client = "10s"
server = "10s"

[default.storage]
location = "memory"

[default.analytics]
collectioninterval = 10
routename = "/analytics"

[default.errorresponses]
errorpagebuttonname = "Comeata"
errorpagebuttonurl = "https://youtube.com"

[frontend]
backend = "shiroxy-test"

[frontend.bind]
port = "8080"
host = ""

[frontend.bind.secure]
target = "single"
singletartgetmode = "certandkey/shiroxysignlesecure"

[frontend.bind.secure.certandkey]
cert = "cert-location"
key = "key-location"

[frontend.bind.secure.shiroxysignlesecure]
domain = "shikharcode.com"
frontend.options = ["http-server-close", "forwardfor"]
secure = false
secureverify = "required"
defaultbackend = ""
fallbackbackend = ""
balance = "round-robin"

[backend]
name = "shiroxy-test"

[[backend.servers]]
id = "<backend-name-server-1>"
host = ""
port = "8001"
healthurl = ""

[[backend.servers]]
id = "<backend-name-server-1>"
host = ""
port = "8002"
healthurl = ""
healthcheckmode = "home/url"
healthchecktriggerduration = 5

[logging]
enable = true
mode = "native/http/native-http"
logging.schema = ["[date-time] "]
logging.include = ["*", ""]

[[webhook]]
enable = true
webhook.events = [""]
url = ""

[health]
enable = true

[health.bind]
host = "*"
port = ""

[health.auth]
user = ""
password = ""
